name: CI/CD

on:
  push:
    tags: ["v*"]

jobs:

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Run test
      run: make test
    - name: Build
      run: make
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ github.ref_name }}
        draft: true
        artifacts: "build/*"
        generateReleaseNotes: true
        makeLatest: "legacy"
